config/routes.rb
Rails.application.routes.draw do

  resources:tweets,only:[:index,:new,:create,:edit,:update,:destroy] do
    collection do
      post:confirm
    end
  end
  
  root 'top#index'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
    validates :content, presence: true, length:{maximum:140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet,only:[:edit,:update,:destroy]
  
  def index
    @tweets = Tweet.all
  end
  
  def new
    if params[:back]
     @tweet = Tweet.new(tweets_params)
    else
      @tweet = Tweet.new
    end
  end
  
  def create
    @tweet = Tweet.create(tweets_params)
    if @tweet.save
     redirect_to tweets_path,notice:"作成しました！"
    else
      render 'new'
    end
  end
  
  def edit
 
  end
  
  def update
    @tweet.update(tweets_params)
    if @tweet.save
      redirect_to tweets_path,notice: "更新しました！"
    else
      render 'edit'
    end
  end
  
  def destroy
    @tweet.destroy
    redirect_to tweets_path, notice: "削除しました！"
  end
  
  def confirm
    @tweet = Tweet.new(tweets_params)
    render :new if @tweet.invalid?
  end
  
    
  private
   def tweets_params
     params.require(:tweet).permit(:title, :content)
   end
   
   def set_tweet
     @tweet = Tweet.find(params[:id])
   end
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def choose_new_or_edit
   if action_name == 'new' || action_name == 'confirm'
      confirm_tweets_path
   elsif action_name == 'edit'
      tweet_path
   end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eaxm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name = "viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  
  <header>
    <ul>
      <li><%= link_to "トップ", root_path %></li>
      <li><%= link_to "つぶやき", new_tweet_path %></li>
      <li><%= link_to "つぶやき一覧", tweets_path %></li>
    </ul>
  </header>

<%= yield %>

<footer>
  <p>大課題１</p>
  <p>2017/6/1</p>
</footer>

</body>
</html>

app/views/top/index.html.erb
 <section class="main-header">
        <img src="<%= asset_path "origin.png" %>">
        </section>
        <section class="about">
         <p><%= notice %></p>
        
        <p>
            これはツイッターではなく、つぶやきです。
        </p>
        </section>
        
          

app/views/tweets/_form.html.erb
<%= form_for(@tweet, url: choose_new_or_edit) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= @tweet.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :content %>
  <%= f.text_field :content, class: 'form-control'%>
  <br>
  <%= f.submit '投稿', class:'btn btn-primary btn-block'%>
<% end %>

<%= link_to "一覧にもどる", tweets_path %>

app/views/tweets/confirm.html.erb
<div class = "container">
  <div class = "col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

<h3>以下の内容で、送信する。</h3>

<%= form_for(@tweet) do |f| %>

  <%= f.hidden_field :content %>

  <p>本文:<%= @tweet.content %></p>
  <%= f.submit "登録する" ,class: 'btn btn-primary btn-block'%>
<% end %>

<%= form_for(@tweet, url: new_tweet_path, method: 'get') do |f| %>
 
  <%= f.hidden_field :content %>
  <%= f.submit "もどる", name: 'back' %>
<% end %>

</div>
</div>

app/views/tweets/edit.html.erb
<div class="container">
    <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>編集する</h2>
    <%= render 'form' %>

     </div>
</div>

app/views/tweets/index.html.erb
<div class = "container">
  <div class = "wrapper col-md-12 col-md-offset-2-sm-10">

<p><%= notice %></p>

<h1>つぶやき一覧</h1>


<% @tweets.each do |tweet| %>
<div class = "row">
  <p>本文:<%= tweet.content %></p>
  <%= link_to "編集する", edit_tweet_path(tweet.id),class:'btn btn-default btn-sm btn-success'%>
  <%= link_to "削除する", tweet_path(tweet.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class:'btn btn-default btn-sm btn btn-danger' %>
  </div>
<% end %>
<%= link_to "つぶやきを作成する", new_tweet_path %>
</div>
</div>

app/views/tweets/new.html.erb
<div class="container">
    <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>作成する</h2>
    <%= render 'form' %>
    </div>
</div>